name: Tests

on: [push, pull_request]

jobs:
  test-macos:
    runs-on: macos-latest
    name: Test on macOS
    steps:
      - uses: actions/checkout@v4
      - name: Install Bats
        run: brew install bats-core
      - name: Run tests
        run: bats --tap tests/

  test-linux:
    runs-on: ubuntu-latest
    name: Test on Linux
    steps:
      - uses: actions/checkout@v4
      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
          cd /tmp/bats-core
          sudo ./install.sh /usr/local
      - name: Run tests
        run: bats --tap tests/
